// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX1CLZWELxfBUqceRc0rPSxqp1LD0VTBQ',
    appId: '1:269191977187:web:2ca1887539b4ee93708dd6',
    messagingSenderId: '269191977187',
    projectId: 'dementia-credentials',
    authDomain: 'dementia-credentials.firebaseapp.com',
    storageBucket: 'dementia-credentials.firebasestorage.app',
    measurementId: 'G-11FFY5E8ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2G4MUDHCzo3ucOnSKB8XxhaHZcMYoSQ',
    appId: '1:269191977187:android:06cb90288ed08c0a708dd6',
    messagingSenderId: '269191977187',
    projectId: 'dementia-credentials',
    storageBucket: 'dementia-credentials.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLpz2ZHvGVnboduVR8VKiAXfFmUcLcrk',
    appId: '1:269191977187:ios:49ee00f559e04346708dd6',
    messagingSenderId: '269191977187',
    projectId: 'dementia-credentials',
    storageBucket: 'dementia-credentials.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLpz2ZHvGVnboduVR8VKiAXfFmUcLcrk',
    appId: '1:269191977187:ios:49ee00f559e04346708dd6',
    messagingSenderId: '269191977187',
    projectId: 'dementia-credentials',
    storageBucket: 'dementia-credentials.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX1CLZWELxfBUqceRc0rPSxqp1LD0VTBQ',
    appId: '1:269191977187:web:602354d66f9e9b81708dd6',
    messagingSenderId: '269191977187',
    projectId: 'dementia-credentials',
    authDomain: 'dementia-credentials.firebaseapp.com',
    storageBucket: 'dementia-credentials.firebasestorage.app',
    measurementId: 'G-DVWP2X97HS',
  );
}
